// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.Data;

#nullable disable

namespace SocialMedia.Data.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240302164122_SeedStatisticEntity")]
    partial class SeedStatisticEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "22a1d95e-a505-4934-9f76-178c3798d64a",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "23fd43c7-113f-4b97-8d21-6cd8661b96b1",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7ca7b293-0236-47cf-88d8-5165102b89ad",
                            RoleId = "22a1d95e-a505-4934-9f76-178c3798d64a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(26);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7ca7b293-0236-47cf-88d8-5165102b89ad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b89378b-254b-4ffd-aa47-6d21fc4d1ae9",
                            CountryId = 26,
                            Email = "admin@socialmedia.com",
                            EmailConfirmed = true,
                            FirstName = "Georgi",
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SOCIALMEDIA.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDNSW9yTPWwXF4HlE4d2Y+82PeSePnaVdvlbax/GtlqK7u0utwMxJIctunq3GJz1w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d8eb8cdc-7d9d-4eea-aae4-9d2a76ea9225",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 51,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 59,
                            Name = "France"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 75,
                            Name = "India"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Korea, North"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Korea, South"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Palestine State"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 149,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 161,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 184,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("SocialMedia.Data.Models.LikedPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedPosts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ReportPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("ReportsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("ReportPosts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllTimeUsersCount")
                        .HasColumnType("int");

                    b.Property<int>("ReportedPostsDeletedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllTimeUsersCount = 0,
                            ReportedPostsDeletedCount = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.LikedPost", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("LikedPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Data.Models.ApplicationUser", "User")
                        .WithMany("LikedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Post", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.ApplicationUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ReportPost", b =>
                {
                    b.HasOne("SocialMedia.Data.Models.Post", "Post")
                        .WithMany("ReportPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("LikedPosts");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SocialMedia.Data.Models.Post", b =>
                {
                    b.Navigation("LikedPosts");

                    b.Navigation("ReportPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
